version: '3.8'

services:
  web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    working_dir: /var/www/html
    container_name: trivial-php
    restart: unless-stopped
    networks:
      - cloudflare_default
    command: >
      bash -c "mkdir -p /var/www/html/Ficheros &&
      touch /var/www/html/Ficheros/datos /var/www/html/Ficheros/jugadores &&
      chmod 777 /var/www/html/Ficheros &&
      chmod 666 /var/www/html/Ficheros/datos /var/www/html/Ficheros/jugadores &&
      chown -R www-data:www-data /var/www/html/Ficheros &&
      sed -i 's/DirectoryIndex.*/DirectoryIndex index.php index.html/g' /etc/apache2/mods-enabled/dir.conf &&
      a2enmod rewrite &&
      apache2-foreground"

networks:
  cloudflare_default:
    external: true
