version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: trivial
    networks:
      - cloudflare_default

  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    container_name: trivial-php
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - cloudflare_default

networks:
  cloudflare_default:
    external: true

